"""Static question data for the Martinelli psychological assessment."""

BIG_FIVE_QUESTIONS = [
    {"num": 1, "text": "Gosto de ser visto como um(a) líder.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 2, "text": "Gosto de que os outros pensem que falo coisas inteligentes.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 3, "text": "Me considero uma pessoa que se importa com o bem-estar dos demais.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 4, "text": "Costumo falar o que penso sobre as pessoas ou situações.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 5, "text": "Aprecio fazer coisas diferentes do que faço normalmente.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 6, "text": "Penso que as pessoas normalmente são bem intencionadas.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 7, "text": "Acredito que sou uma pessoa divertida.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 8, "text": "Procuro sempre tomar cuidado com o que falo para os demais.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à Ponderação"},
    {"num": 9, "text": "Gosto de me desafiar e desempenhar tarefas que me exijam esforço.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 10, "text": "Costumo me divertir quando estou com muitas pessoas.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 11, "text": "Gosto que os trabalhos que desenvolvo sejam precisos, organizados e bem apresentados.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 12, "text": "Costumo influenciar os outros.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 13, "text": "Me considero uma pessoa generosa.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 14, "text": "Não me sinto satisfeito(a) comigo mesmo(a).", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 15, "text": "Me considero uma pessoa que gosta de falar.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 16, "text": "Costumo resolver meus problemas após pensar muito.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à Ponderação"},
    {"num": 17, "text": "Costumo me preocupar com todos os que estão à minha volta.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 18, "text": "Normalmente me sinto feliz.", "factor": "DINAMISMO", "sub_factor": "Tendência ao Dinamismo"},
    {"num": 19, "text": "É comum que eu tome decisões sem pensar muito antes de tomá-las.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 20, "text": "Prefiro me sentir livre para ir e vir quando bem entender.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 21, "text": "Tenho a habilidade de lidar com muitas tarefas ao mesmo tempo.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 22, "text": "Costumo me sentir desanimado(a).", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 23, "text": "Dificilmente suspeito das intenções das pessoas para comigo.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 24, "text": "Costumo conseguir o que desejo.", "factor": "DINAMISMO", "sub_factor": "Tendência ao Dinamismo"},
    {"num": 25, "text": "Costumo dedicar bastante do meu tempo para fazer as coisas da forma correta.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 26, "text": "Não me considero uma pessoa tímida.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 27, "text": "Não abandono os problemas até resolvê-los.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 28, "text": "Vejo minha vida como vazia e sem objetivo.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 29, "text": "Costumo começar de forma rápida as tarefas que preciso fazer, sem procrastinar.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 30, "text": "Costumo respeitar a opinião dos demais.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 31, "text": "Procuro evitar trabalhos que tenham uma rotina fixa.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 32, "text": "Costumo sempre pensar no que pode acontecer antes de agir.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à Ponderação"},
    {"num": 33, "text": "Costumo me sentir mal se prometo algo e não cumpro.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 34, "text": "Costumo preferir atividades em grupo.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 35, "text": "Penso que vejo na vida mais infelicidade do que felicidade.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 36, "text": "Gosto de conhecer novos lugares.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 37, "text": "Costumo conversar com muitas pessoas diferentes quando vou a reuniões sociais.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 38, "text": "Costumo agir de forma impulsiva na maior parte do tempo.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 39, "text": "Aprecio uma vida social intensa.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 40, "text": "Costumo me esforçar para ter destaque no que faço.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 41, "text": "Não penso que as pessoas falam negativamente de mim.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 42, "text": "Costumo me sacrificar para obter o que preciso.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 43, "text": "Costumo motivar as pessoas.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 44, "text": "Procuro sempre pensar no que preciso fazer para atingir minhas metas.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 45, "text": "Me considero uma pessoa ansiosa na maior parte do tempo.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 46, "text": "Costumo me comunicar facilmente com estranhos.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 47, "text": "Pretendo ser considerado(a) uma autoridade em alguma profissão.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 48, "text": "Normalmente confio no que as pessoas me falam.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 49, "text": "Sinto que não sou capaz de enfrentar os problemas.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 50, "text": "Costumo me envolver facilmente com as pessoas.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 51, "text": "Costumo pensar em diversas soluções para os problemas.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 52, "text": "Sinto que meu humor varia bastante.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 53, "text": "Gosto de ser o centro das atenções.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 54, "text": "As pessoas que convivem comigo me acham detalhista.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 55, "text": "Me sinto capaz de assumir tarefas que considero complexas.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 56, "text": "Busco sair da rotina.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 57, "text": "Desejo que as pessoas comentem minha aparência.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 58, "text": "Me considero uma pessoa que se irrita com facilidade.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 59, "text": "Gosto de estar em grupos e conviver com outras pessoas a maior parte do tempo.", "factor": "EXTROVERSÃO", "sub_factor": "Busca por Interações Sociais"},
    {"num": 60, "text": "Costumo resolver meus problemas com rapidez.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 61, "text": "Costumo sofrer com as dificuldades dos outros.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 62, "text": "As pessoas costumam ter inveja de mim.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 63, "text": "Gosto de pegar caminhos diferentes do que estou acostumado.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 64, "text": "Costumo me preocupar com pessoas que estão passando por momentos difíceis.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 65, "text": "Me considero uma pessoa bastante comunicativa.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 66, "text": "Não acredito que os outros desejam me prejudicar.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 67, "text": "Sinto vontade de falar sobre as coisas que conquistei.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 68, "text": "Costumo escolher as palavras com cuidado antes de falar.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à Ponderação"},
    {"num": 69, "text": "Frequentemente tenho fases em que tudo me incomoda.", "factor": "INSTABILIDADE", "sub_factor": "Instabilidade emocional"},
    {"num": 70, "text": "Dificilmente entrego um trabalho antes de revisá-lo com cuidado.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 71, "text": "Costumo me importar com os sentimentos dos demais.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 72, "text": "Em uma festa, gosto de conversar.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 73, "text": "Me sinto cansado(a) com a vida.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 74, "text": "Costumo tomar a iniciativa no trabalho.", "factor": "DINAMISMO", "sub_factor": "Tendência ao Dinamismo"},
    {"num": 75, "text": "Gosto de receber atenção quando estou em um grupo.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 76, "text": "As pessoas dizem que trabalho muito.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 77, "text": "Costumo me entediar se preciso fazer as mesmas coisas.", "factor": "DINAMISMO", "sub_factor": "Busca por novidades"},
    {"num": 78, "text": "Costumo programar em detalhes o que preciso fazer.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 79, "text": "Costumo tomar a iniciativa nas situações em geral.", "factor": "DINAMISMO", "sub_factor": "Tendência ao Dinamismo"},
    {"num": 80, "text": "Acredito que as pessoas são boas.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 81, "text": "Sou uma pessoa normalmente desinibida.", "factor": "EXTROVERSÃO", "sub_factor": "Comunicação"},
    {"num": 82, "text": "Muitas vezes evito me relacionar com outras pessoas por não me sentir bem para tanto.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 83, "text": "Costumo saber quais são as minhas metas e objetivos.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 84, "text": "Costumo ter dificuldade para dormir de noite.", "factor": "INSTABILIDADE", "sub_factor": "Tendência depressiva"},
    {"num": 85, "text": "Normalmente me esforço para que as pessoas se sintam felizes.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 86, "text": "Faço o que decido, mesmo que as pessoas considerem errado.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 87, "text": "Desejo realizar um grande feito em minha vida.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 88, "text": "Prefiro experimentar novidades em meu dia a dia.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 89, "text": "Costumo perdoar as pessoas.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 90, "text": "Gosto de fazer com que as pessoas se sintam bem.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 91, "text": "Prefiro dizer o que penso.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 92, "text": "Gosto de saber o que as pessoas mais experientes do que eu fizeram anteriormente acerca do problema que preciso solucionar.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 93, "text": "Gosto de saber que posso resolver problemas complexos.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 94, "text": "Gosto de cumprir as tarefas que iniciei.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 95, "text": "Gosto de prestar auxílio às pessoas que precisam.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 96, "text": "Acredito que desempenho bem minhas tarefas.", "factor": "PODER DE ENTREGA", "sub_factor": "Competência nas entregas"},
    {"num": 97, "text": "Tendo a dizer aos outros como eles devem fazer seus trabalhos.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 98, "text": "Desejo que as pessoas comentem sobre mim.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 99, "text": "Tendo a experimentar coisas diferentes, as quais não estou acostumado.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 100, "text": "Quando tenho um trabalho, gosto de iniciar logo e permanecer nele até terminá-lo.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 101, "text": "Costumo aceitar bem ser liderado.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 102, "text": "Tendo a trabalhar horas a fio.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 103, "text": "Tendo a não gostar de situações que possam exigir que eu me comporte de uma forma não escolhida por mim.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 104, "text": "Gosto de viajar para lugares que não conheço.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 105, "text": "Costumo rir e falar de pessoas que fazem coisas que considero erradas.", "factor": "INSTABILIDADE", "sub_factor": "Agressividade Relacional"},
    {"num": 106, "text": "Procuro contar aos demais as coisas que acontecem comigo.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 107, "text": "Gosto de terminar um trabalho antes de começar outro.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 108, "text": "Procuro dizer aos meus superiores que eles fizeram um bom trabalho quando isso acontece.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 109, "text": "Antes de começar um trabalho, gosto de organizar e planejar o que farei e os materiais necessários para tanto.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 110, "text": "Gosto de realizar tarefas que exigem habilidade e esforço.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 111, "text": "Gosto de ter sucesso no que faço.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 112, "text": "Costumo manter meus papéis organizados, seguindo algum sistema.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 113, "text": "Procuro realizar com afinco qualquer trabalho que precise realizar.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 114, "text": "Me sinto bem quando realizo um trabalho difícil.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 115, "text": "Sinto vontade de mandar as pessoas calarem a boca quando discordo delas ou acredito que elas disseram alguma bobagem.", "factor": "INSTABILIDADE", "sub_factor": "Agressividade Relacional"},
    {"num": 116, "text": "Prefiro fazer as coisas do meu jeito, mesmo que os outros não concordem.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 117, "text": "Moraria em outro país.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 118, "text": "Costumo me fixar em um problema até resolvê-lo, mesmo quando a solução é difícil ou pode exigir muito de mim.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 119, "text": "Gosto de conhecer pessoas que nunca vi antes.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 120, "text": "Costumo dividir as minhas coisas com os demais.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 121, "text": "Gosto de influenciar os demais.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 122, "text": "Costumo prestar favores aos outros.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 123, "text": "Costumo seguir instruções e fazer o que me é solicitado.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 124, "text": "Costumo me exigir muito.", "factor": "PODER DE ENTREGA", "sub_factor": "Qualidade e Detalhamento"},
    {"num": 125, "text": "Gosto de pedir sugestões de pessoas que admiro.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 126, "text": "Costumo manter minhas coisas limpas e organizadas em meu local de trabalho.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 127, "text": "Costumo tratar as outras pessoas com bondade e compreensão.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 128, "text": "Gosto de provar comidas diferentes que nunca provei antes.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 129, "text": "Gosto de atrair a atenção das pessoas para mim quando em um grupo.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 130, "text": "Procuro ser o(a) líder nos grupos aos quais pertenço.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 131, "text": "Gosto de ser independente para decidir o que desejo fazer.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 132, "text": "Quando estou em uma reunião, gosto de conduzi-la.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 133, "text": "Quando estou em um grupo, não me importo em fazer o que outra pessoa decidir.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 134, "text": "Prefiro não me sentir pressionado(a) por alguma responsabilidade.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 135, "text": "Quando estou irritado(a), sinto vontade de quebrar coisas.", "factor": "INSTABILIDADE", "sub_factor": "Agressividade Relacional"},
    {"num": 136, "text": "Gosto de perguntar coisas que só eu sei a resposta.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 137, "text": "Sou solidário(a) com pessoas machucadas ou doentes.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 138, "text": "Critico pessoas que ocupam posições de autoridade se acredito ser necessário.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 139, "text": "Me sinto bem em fiscalizar os atos dos demais.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 140, "text": "Muitas vezes posso ser competitivo(a).", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 141, "text": "Procuro ajudar pessoas que tem menos do que eu.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 142, "text": "Gosto de planejar e organizar as coisas.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 143, "text": "Gosto de fazer coisas que considero novas e diferentes.", "factor": "DINAMISMO", "sub_factor": "Lida com as mudanças"},
    {"num": 144, "text": "Penso que gostaria de, no futuro, ter realizado algo que pudesse ser visto como de grande sucesso.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 145, "text": "Quando estou com outras pessoas, gosto de decidir o que o grupo fará.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Dominância"},
    {"num": 146, "text": "Costumo me interessar em conhecer mais sobre a vida de pessoas que admiro.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 147, "text": "Gosto de resolver enigmas ou quebra-cabeças se eles forem desafiadores.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 148, "text": "Gosto que todos saibam se obtive algum sucesso.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 149, "text": "Costumo dar o melhor de mim em tudo que faço.", "factor": "PODER DE ENTREGA", "sub_factor": "Foco no Desempenho"},
    {"num": 150, "text": "Tenho facilidade em perdoar as pessoas quando me magoam.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 151, "text": "Prefiro ser livre para tomar minhas decisões e fazer o que quero.", "factor": "DINAMISMO", "sub_factor": "Busca por Autonomia"},
    {"num": 152, "text": "Não costumo ter inimigos.", "factor": "ALTRUÍSMO", "sub_factor": "Confiança nas pessoas"},
    {"num": 153, "text": "Prefiro usar palavras difíceis, que muitas pessoas desconhecem.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 154, "text": "Gosto de planejar antes de realizar algo que considero difícil.", "factor": "PODER DE ENTREGA", "sub_factor": "Organização"},
    {"num": 155, "text": "Tenho facilidade em colocar minhas ideias em prática.", "factor": "DINAMISMO", "sub_factor": "Tendência ao Dinamismo"},
    {"num": 156, "text": "Aprecio a generosidade e costumo ser generosa com os demais.", "factor": "ALTRUÍSMO", "sub_factor": "Prestar Assistência"},
    {"num": 157, "text": "Costumo contar piadas em festas.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 158, "text": "Respeito os sentimentos das outras pessoas.", "factor": "ALTRUÍSMO", "sub_factor": "Tendência à amabilidade"},
    {"num": 159, "text": "Me sinto bem em falar sobre mim.", "factor": "EXTROVERSÃO", "sub_factor": "Vaidade"},
    {"num": 160, "text": "Costumo elogiar as pessoas que admiro.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 161, "text": "Costumo ficar acordado até tarde para terminar um trabalho.", "factor": "PODER DE ENTREGA", "sub_factor": "Tendência à Persistir"},
    {"num": 162, "text": "Gosto de propor coisas ao grupo que sei que farei melhor do que os demais.", "factor": "EXTROVERSÃO", "sub_factor": "Tendência à exibição"},
    {"num": 163, "text": "Costumo me adaptar aos demais se acredito ser importante.", "factor": "ALTRUÍSMO", "sub_factor": "Capacidade de Subordinação"},
    {"num": 164, "text": "Quando me sinto insultado(a), penso em me vingar.", "factor": "INSTABILIDADE", "sub_factor": "Agressividade Relacional"},
]

BIG_FIVE_STRUCTURE = {
    "INSTABILIDADE": {
        "Instabilidade emocional": [19, 38, 45, 52, 58, 69],
        "Tendência depressiva": [14, 22, 28, 35, 49, 73, 82, 84],
        "Agressividade Relacional": [105, 115, 135, 164],
    },
    "EXTROVERSÃO": {
        "Tendência à exibição": [2, 57, 98, 106, 129, 136, 148, 153, 157, 162],
        "Comunicação": [15, 26, 46, 65, 72, 81],
        "Vaidade": [4, 12, 53, 62, 67, 75, 159],
        "Busca por Interações Sociais": [7, 10, 34, 37, 39, 50, 59],
    },
    "PODER DE ENTREGA": {
        "Tendência à Dominância": [1, 97, 111, 121, 130, 132, 139, 145],
        "Foco no Desempenho": [47, 87, 93, 110, 114, 140, 144, 147, 149],
        "Organização": [11, 109, 112, 126, 142, 154],
        "Tendência à Persistir": [27, 94, 100, 102, 107, 113, 118, 161],
        "Competência nas entregas": [9, 21, 29, 42, 44, 51, 55, 60, 83, 96],
        "Qualidade e Detalhamento": [25, 40, 54, 70, 76, 78, 124],
    },
    "ALTRUÍSMO": {
        "Prestar Assistência": [95, 120, 122, 127, 137, 141, 150, 156],
        "Capacidade de Subordinação": [92, 101, 108, 123, 125, 133, 146, 160, 163],
        "Tendência à amabilidade": [3, 13, 17, 30, 33, 43, 61, 64, 71, 85, 90, 158],
        "Confiança nas pessoas": [6, 23, 41, 48, 66, 80, 89, 152],
        "Tendência à Ponderação": [16, 32, 8, 68],
    },
    "DINAMISMO": {
        "Lida com as mudanças": [88, 99, 104, 117, 119, 128, 143],
        "Busca por Autonomia": [20, 86, 91, 103, 116, 131, 134, 138, 151],
        "Busca por novidades": [5, 31, 36, 56, 63, 77],
        "Tendência ao Dinamismo": [18, 24, 74, 79, 155],
    },
}

STRESS_QUESTIONS = [
    {"num": 1, "text": "No último mês, o quanto você ficou triste por alguma coisa que aconteceu de forma inesperada?"},
    {"num": 2, "text": "No último mês, o quanto você sentiu que não era capaz de controlar coisas importantes em sua vida?"},
    {"num": 3, "text": "No último mês, o quanto você se sentiu nervoso(a) ou estressado(a)?"},
    {"num": 4, "text": "No último mês, o quanto você se sentiu perdendo a confiança na sua habilidade de lidar com seus problemas pessoais?"},
    {"num": 5, "text": "No último mês, o quanto você sentiu que as coisas não estavam ocorrendo como gostaria?"},
    {"num": 6, "text": "No último mês, o quanto você sentiu que não daria conta de tudo o que precisa fazer?"},
    {"num": 7, "text": "No último mês, o quanto você sentiu incapacidade em controlar a irritação?"},
    {"num": 8, "text": "No último mês, o quanto você sentiu que estava perdendo o controle das coisas?"},
    {"num": 9, "text": "No último mês, o quanto você sentiu que estava irritado por conta de coisas que acontecem e estão fora do seu controle?"},
    {"num": 10, "text": "No último mês, quantas vezes sentiu dificuldades tão elevadas que não as conseguiu ultrapassar?"},
]

DEPRESSION_QUESTIONS = [
    {"key": "a", "text": "Eu tenho me sentido capaz de rir das coisas e ver o lado engraçado das situações.",
     "options": ["Sim, como sempre.", "Sim, mas menos.", "Com certeza muito menos do que eu conseguia.", "Não consigo rir."]},
    {"key": "b", "text": "Eu tenho buscado me divertir com as coisas.",
     "options": ["Sim, como sempre.", "Um pouco menos do que eu costumava.", "Com certeza menos do que eu costumava.", "Dificilmente me divirto com as coisas."]},
    {"key": "c", "text": "Eu tenho me culpado de forma desnecessária pelas coisas ruins que acontecem.",
     "options": ["Não, nunca.", "Não é muito comum.", "Sim, muitas vezes.", "Sim, na maior parte das vezes."]},
    {"key": "d", "text": "Tenho me sentido ansioso(a) e preocupado(a) sem nenhuma razão específica.",
     "options": ["Não me sinto assim.", "Sim, algumas vezes.", "Muitas vezes.", "Sim, constantemente."]},
    {"key": "e", "text": "Tenho me sentido assustado(a) e em pânico sem um bom motivo.",
     "options": ["Não tenho me sentido assim.", "Não muito.", "Sim, muitas vezes.", "Sim, a maior parte do tempo."]},
    {"key": "f", "text": "Sinto que não tenho dado conta das coisas em geral.",
     "options": ["Não é verdade, tenho lidado tão bem quanto sempre lidei.", "Não é verdade, na maioria das vezes eu lido bem com as coisas.", "Sim, sinto que algumas vezes não tenho conseguido lidar com as coisas.", "Sim, sinto que não tenho conseguido lidar com as coisas na maior parte do tempo."]},
    {"key": "g", "text": "Tenho me sentido tão triste que estou tendo dificuldades para dormir ou sinto sono o tempo todo.",
     "options": ["Não tenho me sentido assim.", "Não com frequência.", "Sim, muitas vezes.", "Sim, na maior parte das vezes."]},
    {"key": "h", "text": "Tenho me sentido triste.",
     "options": ["Não me sinto assim.", "Apenas em alguns momentos.", "Sim, com frequência.", "Sim, a maior parte do tempo."]},
    {"key": "i", "text": "Tenho chorado ultimamente.",
     "options": ["Não tenho chorado.", "Não choro normalmente.", "Sim, choro às vezes.", "Sim, choro a maior parte do tempo."]},
    {"key": "j", "text": "O pensamento de fazer mal para mim mesma(o) tem aparecido.",
     "options": ["Não, nunca.", "Raramente tenho esse tipo de pensamento.", "Às vezes tenho esse tipo de pensamento.", "Sim, tenho tido esse tipo de pensamento com frequência."]},
]

MOTIVATORS_GROUPS = {
    "DINHEIRO": [
        {"num": 1, "text": "O dinheiro é o que mais me motiva no trabalho."},
        {"num": 2, "text": "Abro mão do lazer para ganhar mais."},
        {"num": 3, "text": "Meu maior sonho é ficar rico(a)."},
        {"num": 4, "text": "Ganhar bem é mais importante que trabalhar no que gosto."},
        {"num": 5, "text": "Acho que ter aumento de salário é mais importante do que receber uma promoção."},
        {"num": 6, "text": "Gosto da pressão para alcançar metas desafiadoras, desde que atreladas a bônus e dinheiro."},
        {"num": 7, "text": "Arriscaria abrir um negócio se tivesse chances de ganhar mais."},
        {"num": 8, "text": "Admito trocar um emprego seguro por outro arriscado se ganhar no mínimo 30% a mais."},
        {"num": 9, "text": "Prefiro ganhar por comissão a ter salário fixo."},
        {"num": 10, "text": "Trocaria de profissão para ganhar mais."},
    ],
    "SEGURANÇA": [
        {"num": 11, "text": "Prefiro trabalhos estáveis."},
        {"num": 12, "text": "Bom ambiente de trabalho é o que mais me motiva."},
        {"num": 13, "text": "Segurança no emprego é fundamental."},
        {"num": 14, "text": "Tenho medo de trocar de emprego e me arrepender."},
        {"num": 15, "text": "Sinto-me desconfortável quando há pressão para mudar algo."},
        {"num": 16, "text": "Acho importante ter seguro (de casa, de vida, de carro, etc)."},
        {"num": 17, "text": "Evito trocar o certo pelo duvidoso."},
        {"num": 18, "text": "Não gosto de correr riscos profissionais."},
        {"num": 19, "text": "Prefiro salário fixo, mas garantido."},
        {"num": 20, "text": "Gostaria de passar mais tempo com a família, mesmo ganhando menos."},
    ],
    "APRENDIZADO": [
        {"num": 21, "text": "O aprendizado é minha prioridade."},
        {"num": 22, "text": "Gostaria de conhecer outros setores da empresa em que trabalho, mesmo sem ganhar mais por isso."},
        {"num": 23, "text": "Não me importaria em fazer cursos nos finais de semana."},
        {"num": 24, "text": "Aceitaria ganhar menos se o aprendizado valesse a pena."},
        {"num": 25, "text": "Prefiro trabalhar em locais nos quais haja muitos treinamentos."},
        {"num": 26, "text": "Gosto de ensinar."},
        {"num": 27, "text": "Leio mais livros que a maioria de meus colegas."},
        {"num": 28, "text": "Penso em fazer outra faculdade ou pós-graduação."},
        {"num": 29, "text": "Faria um estágio não remunerado para aprender coisas interessantes."},
        {"num": 30, "text": "Gosto de estudar."},
    ],
    "APROVAÇÃO SOCIAL": [
        {"num": 31, "text": "Gosto de ser reconhecido em público pelos meus feitos."},
        {"num": 32, "text": "Gostaria de ser famoso."},
        {"num": 33, "text": "Procuro ter desempenho melhor de que o de meus colegas."},
        {"num": 34, "text": "Penso que uma promoção seria mais importante que um aumento de salário."},
        {"num": 35, "text": "Gosto de demonstrar meus talentos."},
        {"num": 36, "text": "Prefiro trabalhar em empresas que propiciem rápido crescimento."},
        {"num": 37, "text": "Gostaria de comandar uma equipe maior."},
        {"num": 38, "text": "Penso que receber uma homenagem é mais importante do que receber um prêmio em dinheiro."},
        {"num": 39, "text": "Faria trabalho extra para ser promovido."},
        {"num": 40, "text": "Reparo como os colegas se vestem e procuro me vestir melhor."},
    ],
    "AUTORREALIZAÇÃO": [
        {"num": 41, "text": "Importo-me pouco com dinheiro."},
        {"num": 42, "text": "Adoro minha profissão ou meu trabalho."},
        {"num": 43, "text": "Minha prioridade é ajudar outras pessoas."},
        {"num": 44, "text": "Faço trabalhos voluntários."},
        {"num": 45, "text": "Sinto-me realizado profissionalmente."},
        {"num": 46, "text": "Prefiro trabalhar no que gosto, mesmo que ganhe menos."},
        {"num": 47, "text": "Sinto-me seguro(a) perante a vida."},
        {"num": 48, "text": "Conheço bem meus talentos."},
        {"num": 49, "text": "Conheço bem meus defeitos."},
        {"num": 50, "text": "Sinto profunda paz de espírito."},
    ],
}

DISC_DIMENSIONS = {
    "D": {
        "name": "Dominância",
        "pairs": [
            ("Extremamente gentil", "Extremamente agressivo"),
            ("Não confronta", "Muito confrontador"),
            ("Não exigente", "Muito exigente"),
            ("Muito obediente", "Muito dominante"),
            ("Muito cooperante", "Muito competitivo"),
            ("Muito tolerante", "Muito intolerante"),
            ("Muito harmonioso(a)", "Muito questionador(a)"),
            ("Muito indeciso(a)", "Muito decidido(a)"),
            ("Muito cauteloso(a)", "Muito ousado(a)"),
            ("Muito conciliador(a)", "Muito conflitivo(a)"),
        ],
    },
    "I": {
        "name": "Influência",
        "pairs": [
            ("Muito introvertido(a)", "Muito extrovertido(a)"),
            ("Muito calado(a)", "Muito falante"),
            ("Muito discreto(a)", "Indiscreto(a)"),
            ("Muito fechado(a)", "Muito sociável"),
            ("Muito retraído(a)", "Muito expansivo(a)"),
            ("Muito sério(a)", "Muito brincalhão/ona"),
            ("Odeia festas", "Gosta muito de festas"),
            ("Muito frio(a)", "Muito caloroso(a)"),
            ("Muito inibido(a)", "Muito desinibido(a)"),
            ("Sem emoção", "Muito emotivo(a)"),
        ],
    },
    "S": {
        "name": "Estabilidade",
        "pairs": [
            ("Muito intranquilo(a)", "Muito tranquilo(a)"),
            ("Muito rápido(a)", "Muito lento(a)"),
            ("Muito instável", "Muito estável"),
            ("Muito impaciente", "Muito paciente"),
            ("Muito agitado(a)", "Muito calmo(a)"),
            ("Muito ansioso(a)", "Muito sereno(a)"),
            ("Muda demais", "Odeia mudanças"),
            ("Muito acelerado(a)", "Muito vagaroso(a)"),
            ("Muito impulsivo(a)", "Muito reflexivo(a)"),
            ("Odeia rotina", "Gosta muito de rotina"),
        ],
    },
    "C": {
        "name": "Conformidade",
        "pairs": [
            ("Odeia detalhes", "Muito detalhista"),
            ("Muito desorganizado(a)", "Muito organizado(a)"),
            ("Improvisa demais", "Muito previsível"),
            ("Flexível demais", "Muito inflexível"),
            ("Muito intuitivo(a)", "Muito analítico(a)"),
            ("Muito criativo(a)", "Muito conservador(a)"),
            ("Muito adaptável", "Muito rígido(a)"),
            ("Muito informal", "Muito formal"),
            ("Muito indisciplinado(a)", "Muito disciplinado(a)"),
            ("Muito arbitrário(a)", "Muito metódico(a)"),
        ],
    },
}

QA_QUESTIONS = [
    {"num": 1, "text": "Costumo transformar as situações adversas em algo que possa ser positivo."},
    {"num": 2, "text": "Quando algo sai errado, costumo pensar em soluções ao invés de me lamentar pelo ocorrido."},
    {"num": 3, "text": "Costumo ter facilidade para resolver os problemas."},
    {"num": 4, "text": "Costumo levar com bom humor as adversidades."},
    {"num": 5, "text": "Costumo me comportar de forma diferente, dependendo da situação, para me adaptar."},
    {"num": 6, "text": "Costumo ver o futuro sem me preocupar."},
    {"num": 7, "text": "Quando estou no trânsito costumo me manter calmo(a), mesmo quando estou atrasado(a)."},
    {"num": 8, "text": "Quando me sinto frustrado(a) por algum motivo, não dura muito tempo, consigo logo pensar em uma forma de lidar com o problema."},
    {"num": 9, "text": "Lido bem com situações incertas ou que me despertem raiva."},
    {"num": 10, "text": "Costumo tentar novas formas de fazer as coisas."},
    {"num": 11, "text": "Costumo me perguntar o que aprendi com as situações quando elas dão errado."},
    {"num": 12, "text": "Costumo me sentir fortalecido ao enfrentar situações difíceis."},
    {"num": 13, "text": "Tenho facilidade de me posicionar frente às dificuldades."},
    {"num": 14, "text": "Sou otimista, sempre confio que os problemas irão se resolver."},
    {"num": 15, "text": "Sou flexível."},
    {"num": 16, "text": "Quando algo de ruim acontece, costumo dividir as situações com outras pessoas ao invés de me isolar e ruminar sozinho meus pensamentos."},
    {"num": 17, "text": "Costumo me adaptar facilmente às pessoas com personalidades diferentes da minha."},
    {"num": 18, "text": "Me considero uma pessoa capaz, que tem confiança em si mesma."},
    {"num": 19, "text": "Não me considero vítima das situações e não costumo procurar culpados."},
    {"num": 20, "text": "Tenho facilidade para me reposicionar diante das adversidades, costumo ter facilidade para mudar um plano de ação e começar do zero, se for necessário."},
]
